### ISSUE TITLE
Chromosome length used in grid simulations

### ISSUE THREAD

**Issue by alanaw1** [Arslan-Zaidi/popstructure#1]
Hi @Arslan-Zaidi, I am trying to reproduce some figures from your paper, and was confused by the genotype simulation script. In the paper, it is mentioned that the genome length is 10Mb = 10 chromosomes x 1Mb (per chromosome). 

![Screen Shot 2021-02-18 at 11 06 39 AM](https://user-images.githubusercontent.com/29695123/108425589-83f62080-71ef-11eb-8bd8-2b96d49d5771.png)

However, in the script `generate_genos_grid.py`, I see that the default chromosome length is 10,000,000 bases. See line 14 of the script [here](https://github.com/Arslan-Zaidi/popstructure/blob/master/code/simulating_genotypes/grid/generate_genos_grid.py). This makes me think that your script simulates a genome of length 100Mb = 10 chromosomes x 10Mb (per chromosome). 

My hunch is that it might be the case that 100Mb chromosomes were simulated, rather than 10Mb as the main text describes. I wanted to check with you if this is the case.

My initial confusion came about as I was trying to perform PCA on genotypes simulated under the recent structure model. I ran `msprime` with parameters set as described in the main text attached above, and noticed two discrepancies between my PCA and yours (the latter seen in Figure 1 of your paper). For the recent structure simulation (where demes coalesce t=100 generations ago):

1. The number of filtered variants for rare variant PCA did not match. I yielded 17,900 SNPs with MAC = 2,3,4 (using `mac --2` and `max-mac --4` as per [this script](https://github.com/Arslan-Zaidi/popstructure/blob/master/code/simulating_genotypes/grid/tau100/pca_t100.sh)), but Figure 1 caption states that roughly 750,000 SNPs are kept after applying the MAC filters. (When running `mac --1` and `max-mac --4` as per an older version of your script, I yielded 74621 SNPs.) My yield is an order of magnitude smaller than the reported yield.  
2. PCA returned a markedly different figure. Bottom right of your Figure 1 shows a reasonable gradient of individuals projected onto PCs 1 and 2, but the figure I obtained from performing PCA on the 74621 alleles looks like this. (Note I use the same  colour scale you use in lines 32-43 of [this script](https://github.com/Arslan-Zaidi/popstructure/blob/master/code/pca_plots/plt_pca.R).)   
![Screen Shot 2021-02-18 at 2 04 37 PM](https://user-images.githubusercontent.com/29695123/108427702-6ecec100-71f2-11eb-8a61-a14a7e2ebf06.png)

I am probably mistaken, but if my confusion is valid, please let me know. Thanks!

**Comment by kristjanmoore** [comment]
This issue is a little old now, but I think you may have missed this line in the methods!

> In all cases, after selecting the appropriate migration parameters, we re-simulated genotypes under each model for a larger genome of 200 Mb (20 chromosomes of 10 Mb each), which we used for all further analysis.

Also, `--mac 1` will keep singletons, and even though PLINK happily includes singletons when you tell it to `--pca`, they really aren't informative and you *should* remove them unless you have some strange reason not to.

**Comment by Arslan-Zaidi** [comment]
Hi @alanaw1. So sorry I completely missed this. I don't know if you're still looking for a response to this but basically I remember simulating 10Mb (1Mb x 10 chromosomes) to optimize the migration rate (even though the default in the script is 1e5 Mb). 

As @kristjanmoore pointed out, the results of all further analyses were based on a second set of simulations which were run after the migration parameter was chosen.

So, it makes sense that you're seeing fewer variants than what I reported and that your figure has less resolution than the Fig. 1 from paper because the latter wsa based on a genome that is an order of magnitude larger.

Hope that helps and happy to answer more questions.
